import type { IMissionData } from "./types";

export const DATA: IMissionData = [
  {
    id: "M-102",
    type: "mission",
    title: "Secure Drop Point Alpha",
    status: "IN_PROGRESS",
    location: "Riga Sector A",
    priority: 1,
    lastUpdate: "2025-11-13T10:00:00Z",
  },
  {
    id: "R-204",
    type: "resupply",
    title: "Deliver Power Cells to Forward Base Echo",
    status: "PENDING",
    location: "Daugava Corridor",
    priority: 2,
    lastUpdate: "2025-11-13T10:05:00Z",
  },
  {
    id: "I-309",
    type: "intel",
    title: "Drone Recon Over Sector Foxtrot",
    status: "COMPLETED",
    location: "Foxtrot Ridge",
    priority: 3,
    lastUpdate: "2025-11-13T10:10:00Z",
  },
  {
    id: "M-401",
    type: "mission",
    title: "Establish Forward Observation Post",
    status: "PENDING",
    location: "Cesis Woods",
    priority: 4,
    lastUpdate: "2025-11-13T09:45:00Z",
  },
  {
    id: "R-505",
    type: "resupply",
    title: "Refuel Drone Fleet Charlie",
    status: "IN_PROGRESS",
    location: "Ventspils Port",
    priority: 5,
    lastUpdate: "2025-11-13T10:20:00Z",
  },
  {
    id: "I-612",
    type: "intel",
    title: "Intercept Enemy Radio Signals",
    status: "FAILED",
    location: "Kurzeme Ridge",
    priority: 6,
    lastUpdate: "2025-11-13T09:30:00Z",
  },
  {
    id: "M-703",
    type: "mission",
    title: "Escort Supply Convoy Delta",
    status: "IN_PROGRESS",
    location: "Jelgava Highway",
    priority: 7,
    lastUpdate: "2025-11-13T10:25:00Z",
  },
  {
    id: "R-804",
    type: "resupply",
    title: "Deliver Medical Supplies to Bravo Base",
    status: "COMPLETED",
    location: "Valmiera Outpost",
    priority: 8,
    lastUpdate: "2025-11-13T10:40:00Z",
  },
];
