import type { ITheater, IMission, IEdgeFeed, IAlert } from "./types";

export const THEATERS: ITheater[] = [
  {
    id: "theater-baltic",
    name: "Baltic AO",
    region: "Europe",
    code: "EU-BALTIC",
  },
  {
    id: "theater-indo",
    name: "Indo-Pacific AO",
    region: "Indo-Pacific",
    code: "INDO-PAC",
  },
];

export const MISSIONS: IMission[] = [
  {
    id: "mission-baltic-convoy-21",
    name: "Baltic Convoy Resupply 21",
    theaterId: "theater-baltic",
    priority: 5,
    status: "ACTIVE",
    windowStart: "2025-11-14T10:00:00Z",
    windowEnd: "2025-11-14T22:00:00Z",
  },
  {
    id: "mission-baltic-isr-07",
    name: "Baltic ISR Patrol 07",
    theaterId: "theater-baltic",
    priority: 4,
    status: "ACTIVE",
    windowStart: "2025-11-14T06:00:00Z",
    windowEnd: "2025-11-14T18:00:00Z",
  },
  {
    id: "mission-indo-port-defense-03",
    name: "Port Defense Readiness 03",
    theaterId: "theater-indo",
    priority: 3,
    status: "PLANNING",
    windowStart: "2025-11-15T02:00:00Z",
    windowEnd: "2025-11-15T12:00:00Z",
  },
];

export const FEEDS: IEdgeFeed[] = [
  {
    id: "feed-convoy21-telemetry",
    name: "Convoy 21 – Telemetry",
    missionId: "mission-baltic-convoy-21",
    theaterId: "theater-baltic",
    feedType: "TELEMETRY",
    status: "DEGRADED",
    lastHeartbeatAt: "2025-11-14T13:58:00Z",
    lastDataAt: "2025-11-14T13:40:00Z",
    errorRate: 0.23,
    queuedActions: 5,
    tags: ["convoy", "armored", "cellular-backhaul"],
  },
  {
    id: "feed-convoy21-position",
    name: "Convoy 21 – Position",
    missionId: "mission-baltic-convoy-21",
    theaterId: "theater-baltic",
    feedType: "POSITION",
    status: "OFFLINE",
    lastHeartbeatAt: "2025-11-14T13:20:00Z",
    lastDataAt: "2025-11-14T13:10:00Z",
    errorRate: 0.9,
    queuedActions: 12,
    tags: ["gps", "satcom"],
  },
  {
    id: "feed-isr07-video",
    name: "ISR 07 – Video",
    missionId: "mission-baltic-isr-07",
    theaterId: "theater-baltic",
    feedType: "VIDEO",
    status: "ONLINE",
    lastHeartbeatAt: "2025-11-14T13:59:30Z",
    lastDataAt: "2025-11-14T13:59:25Z",
    errorRate: 0.02,
    queuedActions: 0,
    tags: ["uav", "video", "low-latency"],
  },
  {
    id: "feed-isr07-telemetry",
    name: "ISR 07 – Telemetry",
    missionId: "mission-baltic-isr-07",
    theaterId: "theater-baltic",
    feedType: "TELEMETRY",
    status: "ONLINE",
    lastHeartbeatAt: "2025-11-14T13:59:00Z",
    lastDataAt: "2025-11-14T13:58:50Z",
    errorRate: 0.05,
    queuedActions: 1,
    tags: ["uav", "telemetry"],
  },
  {
    id: "feed-portdefense03-chat",
    name: "Port Defense 03 – Chat",
    missionId: "mission-indo-port-defense-03",
    theaterId: "theater-indo",
    feedType: "CHAT",
    status: "ONLINE",
    lastHeartbeatAt: "2025-11-14T13:57:00Z",
    lastDataAt: "2025-11-14T13:56:00Z",
    errorRate: 0.01,
    queuedActions: 0,
    tags: ["ops-center", "chat"],
  },
];

export const ALERTS: IAlert[] = [
  {
    id: "alert-1",
    missionId: "mission-baltic-convoy-21",
    feedId: "feed-convoy21-position",
    severity: "CRITICAL",
    type: "HEARTBEAT_LOST",
    message: "Position feed lost heartbeat for Convoy 21.",
    createdAt: "2025-11-14T13:25:00Z",
    acknowledged: false,
  },
  {
    id: "alert-2",
    missionId: "mission-baltic-convoy-21",
    feedId: "feed-convoy21-telemetry",
    severity: "WARNING",
    type: "HIGH_ERROR_RATE",
    message: "High telemetry error rate on Convoy 21 link.",
    createdAt: "2025-11-14T13:45:00Z",
    acknowledged: false,
  },
  {
    id: "alert-3",
    missionId: "mission-baltic-isr-07",
    feedId: "feed-isr07-video",
    severity: "INFO",
    type: "LINK_FLAP",
    message: "Short video link interruption detected on ISR 07.",
    createdAt: "2025-11-14T13:30:00Z",
    acknowledged: true,
  },
  {
    id: "alert-4",
    missionId: "mission-indo-port-defense-03",
    feedId: "feed-portdefense03-chat",
    severity: "WARNING",
    type: "CONFIG_DRIFT",
    message: "Configuration drift detected on Port Defense chat gateway.",
    createdAt: "2025-11-14T12:10:00Z",
    acknowledged: false,
  },
];
